server:
  port: 10997

spring:
  config:
    activate:
      on-profile: uat
  datasource:
    url: jdbc:mysql://database_host:3306/shrimp_generate?useUnicode=true&characterEncoding=utf8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: shrimp_generate
    password: your_database_password
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: your_redis_password
    timeout: 3000


mybatis:
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configuration:
    lazy-loading-enabled: true
    use-generated-keys: false
    default-statement-timeout: 25
    safe-row-bounds-enabled: false
    map-underscore-to-camel-case: true

druid:
  login-username: druidAdmin
  login-password: druidPassword
  reset-enable: true
