spring:
  profiles:
    active: dev
  application:
    name: shrimp-generate-backend
  servlet:
    multipart:
      maxFileSize: 1MB
      maxRequestSize: 10MB
  datasource:
    druid:
      initialSize: 0
      maxActive: 20
      minIdle: 1
      maxWait: 10000
      validationQuery: select 'x'
      testOnBorrow: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 18800
      filters: stat,wall
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
  jackson:
    #日期格式化
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    #设置空如何序列化
    defaultPropertyInclusion: NON_NULL
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true


lz:
  security:
    domain:
      api: false
      tenant: false


##### client & service 公用配置 #####

# Tomcat specifics
server:
  tomcat:
    basedir: ./temp
    background-processor-delay: 30s
    accesslog:
      enabled: false
    remoteip:
      port-header: x-forwarded-proto
      remote-ip-header: x-forwarded-for

# 参考：https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md
pagehelper:
  reasonable: true

#### 系统建康状态 #####
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    base-path: /
    ssl:
      enabled: false
  endpoint:
    health:
      showDetails: always
    shutdown:
      enabled: true
    restart:
      enabled: true
